programmer
    id = "2LabsToGo";
    desc = "Use the Linux GPIO interface to bitbang GPIO lines (Trixie compatible)";
    type = "linuxgpio";
    prog_modes = PM_ISP;
    reset = 6;
    sck = 11;
    sdo = 10;
    sdi = 9;
;
